name: Guardian Deployment Gate

on:
  pull_request:
  push:
    branches: [main, staging]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: odavlstudio/guardian@v1
        with:
          url: https://staging.example.com
          preset: landing
          fail-on: risk
        id: guardian

      - name: Print Guardian verdict
        run: |
          echo "================================"
          echo "Guardian Verdict: ${{ steps.guardian.outputs.verdict }}"
          echo "================================"

      - name: Block unsafe deployments
        if: failure()
        run: |
          echo "Deployment blocked by Guardian."
          echo "Download the HTML report to see what failed."
          exit 1

      - name: Proceed if safe
        if: success()
        run: |
          echo "Guardian says: READY"
          echo "This deployment passed safety checks."
